# Generated by Django 2.2.8 on 2019-12-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_prioritycount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritycount',
            old_name='count',
            new_name='prior_count',
        ),
    ]
